# Python 이미지 기반
FROM python:3.10-slim

# 작업 디렉토리
WORKDIR /app

# 의존성 설치
COPY ./python-app/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# 소스 복사
COPY ./python-app .

# 스케줄러 실행
CMD ["python3", "scheduler.py"]